
package es.mir.juego.component.ws.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.2
 * 2013-04-30T18:25:59.334+02:00
 * Generated source version: 2.7.2
 */

@WebFault(name = "JuegoDniException", targetNamespace = "http://service.ws.component.juego.mir.es/")
public class JuegoDniException_Exception extends Exception {
    
    private es.mir.juego.component.ws.service.JuegoDniException juegoDniException;

    public JuegoDniException_Exception() {
        super();
    }
    
    public JuegoDniException_Exception(String message) {
        super(message);
    }
    
    public JuegoDniException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public JuegoDniException_Exception(String message, es.mir.juego.component.ws.service.JuegoDniException juegoDniException) {
        super(message);
        this.juegoDniException = juegoDniException;
    }

    public JuegoDniException_Exception(String message, es.mir.juego.component.ws.service.JuegoDniException juegoDniException, Throwable cause) {
        super(message, cause);
        this.juegoDniException = juegoDniException;
    }

    public es.mir.juego.component.ws.service.JuegoDniException getFaultInfo() {
        return this.juegoDniException;
    }
}
