package es.redsara.intermediacion.scsp.esquemas.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2013-06-18T10:07:45.186+02:00
 * Generated source version: 2.7.2
 * 
 */
@WebService(targetNamespace = "http://intermediacion.redsara.es/scsp/esquemas/ws", name = "scspws")
@XmlSeeAlso({es.redsara.intermediacion.scsp.esquemas.ws.peticion.ObjectFactory.class, es.redsara.intermediacion.scsp.esquemas.ws.fault.ObjectFactory.class, es.redsara.intermediacion.scsp.esquemas.ws.confirmacionpeticion.ObjectFactory.class, es.redsara.intermediacion.scsp.esquemas.ws.solicitudrespuesta.ObjectFactory.class, es.redsara.intermediacion.scsp.esquemas.ws.respuesta.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Scspws {

    @WebResult(name = "Respuesta", targetNamespace = "http://intermediacion.redsara.es/scsp/esquemas/ws/respuesta", partName = "respuesta")
    @WebMethod(action = "solicitudRespuesta")
    public es.redsara.intermediacion.scsp.esquemas.ws.respuesta.Respuesta solicitudRespuesta(
        @WebParam(partName = "solicitudRespuesta", name = "SolicitudRespuesta", targetNamespace = "http://intermediacion.redsara.es/scsp/esquemas/ws/solicitudRespuesta")
        es.redsara.intermediacion.scsp.esquemas.ws.solicitudrespuesta.SolicitudRespuesta solicitudRespuesta
    ) throws FaultMessage;

    @WebResult(name = "RespuestaPdf", targetNamespace = "http://intermediacion.redsara.es/scsp/esquemas/ws/respuesta", partName = "respuestaPdf")
    @WebMethod(action = "peticionPdf")
    public es.redsara.intermediacion.scsp.esquemas.ws.respuesta.RespuestaPdf peticionPdf(
        @WebParam(partName = "peticionPdf", name = "PeticionPdf", targetNamespace = "http://intermediacion.redsara.es/scsp/esquemas/ws/peticion")
        es.redsara.intermediacion.scsp.esquemas.ws.peticion.PeticionPdf peticionPdf
    ) throws FaultMessage;

    @WebResult(name = "ConfirmacionPeticion", targetNamespace = "http://intermediacion.redsara.es/scsp/esquemas/ws/confirmacionPeticion", partName = "confirmacionPeticion")
    @WebMethod(action = "peticionAsincrona")
    public es.redsara.intermediacion.scsp.esquemas.ws.confirmacionpeticion.ConfirmacionPeticion peticionAsincrona(
        @WebParam(partName = "peticionAsincrona", name = "PeticionAsincrona", targetNamespace = "http://intermediacion.redsara.es/scsp/esquemas/ws/peticion")
        es.redsara.intermediacion.scsp.esquemas.ws.peticion.PeticionAsincrona peticionAsincrona
    ) throws FaultMessage;

    @WebResult(name = "Respuesta", targetNamespace = "http://intermediacion.redsara.es/scsp/esquemas/ws/respuesta", partName = "respuesta")
    @WebMethod(action = "peticionRecover")
    public es.redsara.intermediacion.scsp.esquemas.ws.respuesta.Respuesta peticionRecover(
        @WebParam(partName = "peticionRecover", name = "PeticionRecover", targetNamespace = "http://intermediacion.redsara.es/scsp/esquemas/ws/peticion")
        es.redsara.intermediacion.scsp.esquemas.ws.peticion.PeticionRecover peticionRecover
    ) throws FaultMessage;

    @WebResult(name = "Respuesta", targetNamespace = "http://intermediacion.redsara.es/scsp/esquemas/ws/respuesta", partName = "respuesta")
    @WebMethod(action = "peticionSincrona")
    public es.redsara.intermediacion.scsp.esquemas.ws.respuesta.Respuesta peticionSincrona(
        @WebParam(partName = "peticionSincrona", name = "PeticionSincrona", targetNamespace = "http://intermediacion.redsara.es/scsp/esquemas/ws/peticion")
        es.redsara.intermediacion.scsp.esquemas.ws.peticion.PeticionSincrona peticionSincrona
    ) throws FaultMessage;
}
