package es.dgoj.rgiaj.business.model;
// Generated by Expand 2.2.0 

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * @author ylopezconnectis
 *
 */
@Entity
@Table(name="JUG_HISTORICODESCARGASPROH")
public class JugHistoricodescargasproh  implements java.io.Serializable {

     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id     
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name="ID", unique=true, nullable=false)
	private Long id;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="FECHA_DESCARGA", length=7)
    private Date fechaDescarga;
	
    @Column(name="ULTIMO")
    private Long ultimo;
    
    @Column(name="COMPLETA")
    private Integer completa;
    
	@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ID_COMUNIDAD")
    private JugComunidad jugComunidad;
	
	@Column(name="CONFIRMADA")
	private Integer confirmada;
	
	@Column(name="PROCEDENCIA")
	private String procedencia;
     
    public JugHistoricodescargasproh() {
    }
	
    public JugHistoricodescargasproh(Long id) {
        this.id = id;
    }

    public JugHistoricodescargasproh(Long id, Date fechaDescarga, Long ultimo, Integer completa, JugComunidad jugComunidad) {
       this.id = id;
       this.fechaDescarga = fechaDescarga;
       this.ultimo = ultimo;
       this.completa = completa;
       this.jugComunidad = jugComunidad;
    }

   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
   
    public Date getFechaDescarga() {
        return this.fechaDescarga;
    }
    
    public void setFechaDescarga(Date fechaDescarga) {
        this.fechaDescarga = fechaDescarga;
    }
    
    
    public Long getUltimo() {
        return this.ultimo;
    }
    
    public void setUltimo(Long ultimo) {
        this.ultimo = ultimo;
    }
    
   
    public Integer getCompleta() {
        return this.completa;
    }
    
    public void setCompleta(Integer completa) {
        this.completa = completa;
    }
    
    public JugComunidad getJugComunidad() {
        return this.jugComunidad;
    }
    
    public void setJugComunidad(JugComunidad jugComunidad) {
        this.jugComunidad = jugComunidad;
    }

	public Integer getConfirmada() {
		return confirmada;
	}

	public void setConfirmada(Integer confirmada) {
		this.confirmada = confirmada;
	}

	public String getProcedencia() {
		return procedencia;
	}

	public void setProcedencia(String procedencia) {
		this.procedencia = procedencia;
	}

    
   
}


