package es.dgoj.rgiaj.business.model;

// Generated by Expand 2.2.0 

//import com.transtools.expand.annotation.*;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * @author ylopezconnectis
 *
 */
@Entity
@Table(name = "JUG_MUNICIPIO")
public class JugMunicipio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID", nullable = false, unique = true)
	private Long id;
	
	@Column(name = "CODIGO")
	private Integer codigo;
	
	@Column(name = "DESCRIPCION", nullable = false)
	private String descripcion;
	
	@Column(name = "ACTIVO", nullable = false)
	private Integer activo;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PROVINCIA", nullable = false)
	private JugProvincia jugProvincia;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jugMunicipio")
	private List<JugPersona> jugPersonaList = new ArrayList<JugPersona>(0);

	public JugMunicipio() {
	}

	public JugMunicipio(Long id, String descripcion, Integer activo,
			JugProvincia jugProvincia) {
		this.id = id;
		this.descripcion = descripcion;
		this.activo = activo;
		this.jugProvincia = jugProvincia;
	}

	public JugMunicipio(Long id, Integer codigo, String descripcion,
			Integer activo, JugProvincia jugProvincia,
			List<JugPersona> jugPersonaList) {
		this.id = id;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.activo = activo;
		this.jugProvincia = jugProvincia;
		this.jugPersonaList = jugPersonaList;
	}

	
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	
	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	
	public Integer getActivo() {
		return this.activo;
	}

	public void setActivo(Integer activo) {
		this.activo = activo;
	}


	public JugProvincia getJugProvincia() {
		return this.jugProvincia;
	}

	public void setJugProvincia(JugProvincia jugProvincia) {
		this.jugProvincia = jugProvincia;
	}


	
	public List<JugPersona> getJugPersonaList() {
		return this.jugPersonaList;
	}

	public void setJugPersonaList(List<JugPersona> jugPersonaList) {
		this.jugPersonaList = jugPersonaList;
	}

}
