package es.dgoj.rgiaj.business.model;

// Generated by Expand 2.2.0 

//import com.transtools.expand.annotation.*;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * @author ylopezconnectis
 *
 */
@Entity
@Table(name = "JUG_PROVINCIA")
public class JugProvincia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID", nullable = false, unique = true)
	private Long id;
	
	@Column(name = "CODIGO")
	private String codigo;
	
	@Column(name = "DESCRIPCION", nullable = false)
	private String descripcion;
	
	@Column(name = "ACTIVO", nullable = false)
	private Integer activo;
	
	@Column(name = "MATRICULA")
	private String matricula;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_COMUNIDAD", nullable = false)
	private JugComunidad jugComunidad;
	

	//	private List<JugOrganismo> jugOrganismoList = new ArrayList<JugOrganismo>(0);
//	private List<JugEmpresa> jugEmpresaList = new ArrayList<JugEmpresa>(0);
	

	public JugProvincia() {
	}

	public JugProvincia(Long id, String descripcion, Integer activo,
			JugComunidad jugComunidad) {
		this.id = id;
		this.descripcion = descripcion;
		this.activo = activo;
		this.jugComunidad = jugComunidad;
	}

	public JugProvincia(Long id, String codigo, String descripcion,
			Integer activo, String matricula, JugComunidad jugComunidad
			/*List<JugOrganismo> jugOrganismoList,
			List<JugEmpresa> jugEmpresaList,*/) {
		this.id = id;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.activo = activo;
		this.matricula = matricula;
		this.jugComunidad = jugComunidad;
//		this.jugOrganismoList = jugOrganismoList;
//		this.jugEmpresaList = jugEmpresaList;
	}

	
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	
	public Integer getActivo() {
		return this.activo;
	}

	public void setActivo(Integer activo) {
		this.activo = activo;
	}

	
	public String getMatricula() {
		return this.matricula;
	}

	public void setMatricula(String matricula) {
		this.matricula = matricula;
	}

	
	public JugComunidad getJugComunidad() {
		return this.jugComunidad;
	}

	public void setJugComunidad(JugComunidad jugComunidad) {
		this.jugComunidad = jugComunidad;
	}

//	
//	public List<JugMunicipio> getJugMunicipioList() {
//		return this.jugMunicipioList;
//	}
//
//	public void setJugMunicipioList(List<JugMunicipio> jugMunicipioList) {
//		this.jugMunicipioList = jugMunicipioList;
//	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jugProvincia")
//	public List<JugOrganismo> getJugOrganismoList() {
//		return this.jugOrganismoList;
//	}
//
//	public void setJugOrganismoList(List<JugOrganismo> jugOrganismoList) {
//		this.jugOrganismoList = jugOrganismoList;
//	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jugProvincia")
//	public List<JugEmpresa> getJugEmpresaList() {
//		return this.jugEmpresaList;
//	}
//
//	public void setJugEmpresaList(List<JugEmpresa> jugEmpresaList) {
//		this.jugEmpresaList = jugEmpresaList;
//	}

//	public List<JugPersona> getJugPersonaList() {
//		return this.jugPersonaList;
//	}
//
//	public void setJugPersonaList(List<JugPersona> jugPersonaList) {
//		this.jugPersonaList = jugPersonaList;
//	}

}
